spring.application.name=gestion-projets-academiques
server.port=8081
spring.profiles.active=dev

# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
