# === Dev profile — PostgreSQL local ===
spring.datasource.url=jdbc:postgresql://localhost:5432/gestionprojet
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=never

# JWT
app.jwt.secret=devSecretKey_ChangeInProd_AtLeast256BitsLongForHS256Algorithm123456
app.jwt.expiration-ms=86400000

# File uploads
app.upload.dir=./uploads/rapports

# Swagger / OpenAPI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.show-actuator=false
springdoc.packages-to-scan=com.gestionprojet.gestionprojetacademique.controller
